### ISSUE TITLE
Erro no massban

### ISSUE THREAD

**Issue by uziel-sla** [HordLawk/YottaBot#1]
Não sei oq c queria fazer lá mas na const ids do massban tem erro de sintaxe

**Comment by HordLawk** [comment]
qual o erro

**Comment by uziel-sla** [comment]
Erro de **sintaxe** na const ids

**Comment by HordLawk** [comment]
mas onde ta o erro de sintaxe eu ja procurei e nao achei

**Comment by uziel-sla** [comment]
aí ó
![Screenshot_2021-07-13-19-21-46-589_com discord~2](https://user-images.githubusercontent.com/82796362/125532899-7216fbec-1e27-4ca4-89a0-bbbc16aa2619.jpg)
![Screenshot_2021-07-13-19-23-11-548_com android chrome~2](https://user-images.githubusercontent.com/82796362/125532907-65617167-d531-417f-aaf5-bcdd751e4063.jpg)

**Comment by HordLawk** [comment]
isso é [conditional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) o seu node deve estar desatualizado
